# Docker Compose para Producción
# Mismos servicios que desarrollo, solo cambian nombres de contenedores y archivos .env
services:
  # Base de datos PostgreSQL con pgvector
  db:
    image: ankane/pgvector:latest
    container_name: dealaai_db_prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-dealaai_prod}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - dealaai_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis para cache y Celery
  redis:
    image: redis:7-alpine
    container_name: dealaai_redis_prod
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - dealaai_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Django
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: dealaai_backend_prod
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - backend_media:/app/media
      - backend_static:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - ./backend/.env.production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dealaai_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: dealaai_frontend_prod
    restart: unless-stopped
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    expose:
      - "3000"
    env_file:
      - ./frontend/.env.local.production
    depends_on:
      - backend
    networks:
      - dealaai_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Celery Worker
  celery_worker:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: dealaai_celery_worker_prod
    restart: unless-stopped
    command: celery -A dealaai worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dealaai_network

  # Celery Beat
  celery_beat:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: dealaai_celery_beat_prod
    restart: unless-stopped
    command: celery -A dealaai beat -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dealaai_network

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: dealaai_nginx_prod
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - backend_static:/var/www/static
      - backend_media:/var/www/media
    depends_on:
      - backend
      - frontend
    networks:
      - dealaai_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  backend_media:
    driver: local
  backend_static:
    driver: local

networks:
  dealaai_network:
    driver: bridge
