# Docker Compose para DigitalOcean App Platform
# Configuración optimizada para DigitalOcean
# DigitalOcean maneja automáticamente PostgreSQL y Redis via Managed Databases

version: "3.8"

services:
  # Nginx Reverse Proxy (servicio principal para App Platform)
  web:
    image: nginx:1.25-alpine
    container_name: dealaai_web
    restart: unless-stopped
    ports:
      - "8080:80" # App Platform usa 8080 por defecto
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - backend_static:/var/www/static:ro
      - backend_media:/var/www/media:ro
    depends_on:
      - frontend
      - backend
    networks:
      - dealaai_network
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile.prod
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
        - NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
    container_name: dealaai_frontend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      - NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
    depends_on:
      - backend
    networks:
      - dealaai_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend Django
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile.prod
      args:
        - DJANGO_SETTINGS_MODULE=dealaai.settings.production
    container_name: dealaai_backend
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - backend_static:/app/staticfiles
      - backend_logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=dealaai.settings.production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DEBUG=False
      - SECURE_SSL_REDIRECT=True
      - SESSION_COOKIE_SECURE=True
      - CSRF_COOKIE_SECURE=True
    networks:
      - dealaai_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend_static:
    driver: local
  backend_logs:
    driver: local

networks:
  dealaai_network:
    driver: bridge
