services:
  # Servidor web Apache
  web:
    image: httpd:alpine
    container_name: dealaai_web
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs:ro
    networks:
      - dealaai_network

networks:
  dealaai_network:
    driver: bridge
