# Configuración de Buildpacks para Easypanel
# project.toml es el estándar Cloud Native Buildpacks

[[build.buildpacks]]
uri = "heroku/python"

[[build.buildpacks]]
uri = "heroku/nodejs"

[build.env]
# Variables de entorno para el build
DJANGO_SETTINGS_MODULE = "dealaai.settings.production"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
