# Generated by Django 4.2.7 on 2025-10-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idv", models.IntegerField(blank=True, db_index=True, null=True)),
                ("fecha_informe", models.IntegerField(blank=True, null=True)),
                (
                    "bastidor",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Bastidor (VIN)"
                    ),
                ),
                (
                    "vehicle_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "vehicle_key2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "id_concesionario",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "nom_concesionario",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "id_proveedor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nom_proveedor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dealer_corto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "provincia",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("fecha_matriculacion", models.DateField(blank=True, null=True)),
                ("fecha_recepcion", models.DateField(blank=True, null=True)),
                (
                    "marca",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modelo_comercial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("id_modelo", models.CharField(blank=True, max_length=100, null=True)),
                ("modelo_qbi", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "descripcion_modelo_qbi",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "modelo_bastidor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("anio_matricula", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "color_secundario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cod_color", models.CharField(blank=True, max_length=50, null=True)),
                ("id_color", models.CharField(blank=True, max_length=100, null=True)),
                ("kilometros", models.IntegerField(blank=True, null=True)),
                ("ubicacion", models.CharField(blank=True, max_length=100, null=True)),
                ("id_tipo_vo", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "descripcion_tipo_vo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "id_estado",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "descripcion_estado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tipo_stock", models.CharField(blank=True, max_length=50, null=True)),
                ("reservado", models.BooleanField(db_index=True, default=False)),
                ("dias_stock", models.IntegerField(blank=True, null=True)),
                (
                    "intervalo_dias",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "meses_en_stock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("dias_stock_fin_mes", models.IntegerField(blank=True, null=True)),
                (
                    "intervalo_dias_fin_mes",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "intervalo_dias_vo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "intervalo_dias_vo_new",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "intervalo_km",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "interv_km_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("uds_disponibles_stock", models.IntegerField(blank=True, null=True)),
                ("uds_reservadas_stock", models.IntegerField(blank=True, null=True)),
                ("stock_uds", models.IntegerField(blank=True, null=True)),
                ("pedido", models.CharField(blank=True, max_length=100, null=True)),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "canal_entrada_vo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "concepto_compra",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "importe_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "importe_rectificativas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "importe_reacon",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "importe_vales",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "importe_costo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "importe_coste_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "precio_anterior",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "precio_nuevo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "diferencia_precios",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "stock_benef_estimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("publicado", models.BooleanField(db_index=True, default=False)),
                (
                    "id_internet",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("link_internet", models.TextField(blank=True, null=True)),
                (
                    "internet_eurotax_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "internet_eurotax_venta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("internet_anuncios", models.IntegerField(blank=True, null=True)),
                (
                    "internet_precio_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "internet_precio_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "precio_internet",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("internet_fotos", models.IntegerField(blank=True, null=True)),
                ("internet_autorizado", models.BooleanField(default=False)),
                (
                    "status_imaweb",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status_car_imaweb",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_primera_publicacion", models.DateField(blank=True, null=True)),
                ("fecha_ultima_publicacion", models.DateField(blank=True, null=True)),
                ("antiguedad_anuncio", models.IntegerField(blank=True, null=True)),
                ("dias_primera_public", models.IntegerField(blank=True, null=True)),
                ("uc_dias", models.IntegerField(blank=True, null=True)),
                ("internet_dias_public", models.IntegerField(blank=True, null=True)),
                ("tmaimg", models.CharField(blank=True, max_length=100, null=True)),
                ("tiene_video", models.BooleanField(default=False)),
                ("visitas_totales", models.IntegerField(blank=True, null=True)),
                ("llamadas_recibidas", models.IntegerField(blank=True, null=True)),
                ("emails_recibidos", models.IntegerField(blank=True, null=True)),
                ("visitas_cambio", models.IntegerField(blank=True, null=True)),
                ("leads_cambio", models.IntegerField(blank=True, null=True)),
                ("visitas_cambio_dias", models.IntegerField(blank=True, null=True)),
                ("leads_cambio_dias", models.IntegerField(blank=True, null=True)),
                ("flag_lead", models.BooleanField(db_index=True, default=False)),
                ("stock_leads", models.IntegerField(blank=True, null=True)),
                ("prediction", models.CharField(blank=True, max_length=100, null=True)),
                ("uds_mes", models.IntegerField(blank=True, null=True)),
                ("uds_3mes", models.IntegerField(blank=True, null=True)),
                ("uds_ano", models.IntegerField(blank=True, null=True)),
                (
                    "ultimo_cambio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ult_cambio", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_ultimo_cambio", models.DateField(blank=True, null=True)),
                ("fecha_ultimo_cambio_2", models.DateField(blank=True, null=True)),
                ("fecha_ult_cambio", models.DateField(blank=True, null=True)),
                (
                    "dias_desde_ult_cambio",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "bastidor_qbi",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "id_calidad_marca",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                (
                    "fecha_ultima_foto_optipix",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "id_vehiculo_foto_optipix",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("dias_desde_foto_optipix", models.IntegerField(blank=True, null=True)),
                (
                    "status_foto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "id_veces_pospuesto",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("veces_pospuesto", models.IntegerField(blank=True, null=True)),
                ("xxx", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fecha_snapshot",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "fecha_insert",
                    models.DateTimeField(
                        db_index=True, verbose_name="Fecha de inserción en histórico"
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stock Histórico",
                "verbose_name_plural": "Stocks Históricos",
                "db_table": "stock_historico",
                "indexes": [
                    models.Index(
                        fields=["bastidor"], name="stock_histo_bastido_c7578f_idx"
                    ),
                    models.Index(
                        fields=["fecha_snapshot"], name="stock_histo_fecha_s_078704_idx"
                    ),
                    models.Index(
                        fields=["id_concesionario"],
                        name="stock_histo_id_conc_b2de34_idx",
                    ),
                    models.Index(fields=["marca"], name="stock_histo_marca_deb7b7_idx"),
                    models.Index(
                        fields=["modelo"], name="stock_histo_modelo_70b39b_idx"
                    ),
                    models.Index(
                        fields=["matricula"], name="stock_histo_matricu_880ec6_idx"
                    ),
                    models.Index(
                        fields=["publicado"], name="stock_histo_publica_818d89_idx"
                    ),
                    models.Index(
                        fields=["reservado"], name="stock_histo_reserva_67df5c_idx"
                    ),
                    models.Index(
                        fields=["flag_lead"], name="stock_histo_flag_le_60b8a9_idx"
                    ),
                    models.Index(
                        fields=["fecha_insert"], name="stock_histo_fecha_i_507a86_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("idv", models.IntegerField(blank=True, db_index=True, null=True)),
                ("fecha_informe", models.IntegerField(blank=True, null=True)),
                (
                    "bastidor",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Bastidor (VIN)",
                    ),
                ),
                (
                    "vehicle_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "vehicle_key2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "id_concesionario",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "nom_concesionario",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "id_proveedor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nom_proveedor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dealer_corto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "provincia",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("fecha_matriculacion", models.DateField(blank=True, null=True)),
                ("fecha_recepcion", models.DateField(blank=True, null=True)),
                (
                    "marca",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modelo_comercial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("id_modelo", models.CharField(blank=True, max_length=100, null=True)),
                ("modelo_qbi", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "descripcion_modelo_qbi",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "modelo_bastidor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("anio_matricula", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "color_secundario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cod_color", models.CharField(blank=True, max_length=50, null=True)),
                ("id_color", models.CharField(blank=True, max_length=100, null=True)),
                ("kilometros", models.IntegerField(blank=True, null=True)),
                ("ubicacion", models.CharField(blank=True, max_length=100, null=True)),
                ("id_tipo_vo", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "descripcion_tipo_vo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "id_estado",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "descripcion_estado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tipo_stock", models.CharField(blank=True, max_length=50, null=True)),
                ("reservado", models.BooleanField(db_index=True, default=False)),
                ("dias_stock", models.IntegerField(blank=True, null=True)),
                (
                    "intervalo_dias",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "meses_en_stock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("dias_stock_fin_mes", models.IntegerField(blank=True, null=True)),
                (
                    "intervalo_dias_fin_mes",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "intervalo_dias_vo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "intervalo_dias_vo_new",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "intervalo_km",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "interv_km_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("uds_disponibles_stock", models.IntegerField(blank=True, null=True)),
                ("uds_reservadas_stock", models.IntegerField(blank=True, null=True)),
                ("stock_uds", models.IntegerField(blank=True, null=True)),
                ("pedido", models.CharField(blank=True, max_length=100, null=True)),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "canal_entrada_vo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "concepto_compra",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "importe_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "importe_rectificativas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "importe_reacon",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "importe_vales",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "importe_costo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "importe_coste_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "precio_anterior",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "precio_nuevo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "diferencia_precios",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "stock_benef_estimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("publicado", models.BooleanField(db_index=True, default=False)),
                (
                    "id_internet",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("link_internet", models.TextField(blank=True, null=True)),
                (
                    "internet_eurotax_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "internet_eurotax_venta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("internet_anuncios", models.IntegerField(blank=True, null=True)),
                (
                    "internet_precio_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "internet_precio_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "precio_internet",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("internet_fotos", models.IntegerField(blank=True, null=True)),
                ("internet_autorizado", models.BooleanField(default=False)),
                (
                    "status_imaweb",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status_car_imaweb",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_primera_publicacion", models.DateField(blank=True, null=True)),
                ("fecha_ultima_publicacion", models.DateField(blank=True, null=True)),
                ("antiguedad_anuncio", models.IntegerField(blank=True, null=True)),
                ("dias_primera_public", models.IntegerField(blank=True, null=True)),
                ("uc_dias", models.IntegerField(blank=True, null=True)),
                ("internet_dias_public", models.IntegerField(blank=True, null=True)),
                ("tmaimg", models.CharField(blank=True, max_length=100, null=True)),
                ("tiene_video", models.BooleanField(default=False)),
                ("visitas_totales", models.IntegerField(blank=True, null=True)),
                ("llamadas_recibidas", models.IntegerField(blank=True, null=True)),
                ("emails_recibidos", models.IntegerField(blank=True, null=True)),
                ("visitas_cambio", models.IntegerField(blank=True, null=True)),
                ("leads_cambio", models.IntegerField(blank=True, null=True)),
                ("visitas_cambio_dias", models.IntegerField(blank=True, null=True)),
                ("leads_cambio_dias", models.IntegerField(blank=True, null=True)),
                ("flag_lead", models.BooleanField(db_index=True, default=False)),
                ("stock_leads", models.IntegerField(blank=True, null=True)),
                ("prediction", models.CharField(blank=True, max_length=100, null=True)),
                ("uds_mes", models.IntegerField(blank=True, null=True)),
                ("uds_3mes", models.IntegerField(blank=True, null=True)),
                ("uds_ano", models.IntegerField(blank=True, null=True)),
                (
                    "ultimo_cambio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ult_cambio", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_ultimo_cambio", models.DateField(blank=True, null=True)),
                ("fecha_ultimo_cambio_2", models.DateField(blank=True, null=True)),
                ("fecha_ult_cambio", models.DateField(blank=True, null=True)),
                (
                    "dias_desde_ult_cambio",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "bastidor_qbi",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "id_calidad_marca",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                (
                    "fecha_ultima_foto_optipix",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "id_vehiculo_foto_optipix",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("dias_desde_foto_optipix", models.IntegerField(blank=True, null=True)),
                (
                    "status_foto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "id_veces_pospuesto",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("veces_pospuesto", models.IntegerField(blank=True, null=True)),
                ("xxx", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_snapshot", models.DateField(blank=True, null=True)),
                (
                    "fecha_insert",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "db_table": "stock",
                "indexes": [
                    models.Index(fields=["bastidor"], name="stock_bastido_f29b10_idx"),
                    models.Index(
                        fields=["id_concesionario"], name="stock_id_conc_3d7497_idx"
                    ),
                    models.Index(fields=["marca"], name="stock_marca_73dea7_idx"),
                    models.Index(fields=["modelo"], name="stock_modelo_a2389b_idx"),
                    models.Index(fields=["matricula"], name="stock_matricu_4f3085_idx"),
                    models.Index(fields=["publicado"], name="stock_publica_729e23_idx"),
                    models.Index(fields=["reservado"], name="stock_reserva_8c0ea3_idx"),
                    models.Index(fields=["flag_lead"], name="stock_flag_le_39c8d5_idx"),
                    models.Index(
                        fields=["fecha_insert"], name="stock_fecha_i_0f3c83_idx"
                    ),
                ],
            },
        ),
    ]
