# Generated by Django 4.2.7 on 2025-10-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="cilindrada",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="combustible",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="imagen_principal",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="imagenes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="peso",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="plazas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="potencia",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="puertas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="transmision",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="version",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
