# Generated by Django 4.2.7 on 2025-10-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_stock_cilindrada_stock_combustible_stock_descripcion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="cilindrada",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="combustible",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="imagen_principal",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="imagenes",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="peso",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="plazas",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="potencia",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="puertas",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="transmision",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="version",
        ),
        migrations.AddField(
            model_name="stock",
            name="tipo_vehiculo",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockhistorico",
            name="tipo_vehiculo",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
