# Generated by Django 4.2.7 on 2025-10-26 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre de la provincia",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="Código de la provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provincia",
                "verbose_name_plural": "Provincias",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["username"],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="Usuario activo"),
        ),
        migrations.AddField(
            model_name="user",
            name="chat_ai_activo",
            field=models.BooleanField(default=True, verbose_name="Chat con AI activo"),
        ),
        migrations.AddField(
            model_name="user",
            name="fecha_incorporacion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de incorporación"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="fecha_nacimiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de nacimiento"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="jefe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Jefe directo",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="movil",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Teléfono móvil"
            ),
        ),
        migrations.CreateModel(
            name="Concesionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del concesionario"
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.provincia",
                        verbose_name="Provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concesionario",
                "verbose_name_plural": "Concesionarios",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="concesionario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.concesionario",
                verbose_name="Concesionario",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="provincia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.provincia",
                verbose_name="Provincia",
            ),
        ),
    ]
