# Generated by Django 4.2.7 on 2025-10-26 02:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_populate_perfiles"),
        ("authentication", "0004_replace_profile_field"),
    ]

    operations = []
